### ISSUE TITLE
3D Animation Mode:  not observing text_prompt keyframes

### ISSUE THREAD

**Issue by seandearnaley** [entmike/disco-diffusion-1#10]
I have a YAML file with keyframes for the text_prompt parameter but simplified DD doesn't seem to observe them in animation mode... in the following example, I had set another prompt for keyframe 20, but as you can see in the screen shot, it doesn't change the prompt from 0... I have tested this in both colab and docker on lambda labs:
<img width="1700" alt="Screen Shot 2022-05-19 at 3 20 40 PM" src="https://user-images.githubusercontent.com/5084762/169386176-54307581-5ecb-4486-bf70-7466d36966b4.png">

YAML (note: keyframe 20)
```
RN101: false
RN50: true
RN50x16: false
RN50x4: false
RN50x64: false
ViTB16: true
ViTB32: true
ViTL14: false
ViTL14_336: false
angle: 0:(0)
animation_mode: 3D
batch_name: AnimTest7
check_model_SHA: false
clamp_grad: true
clamp_max: 0.26
clip_denoised: false
clip_guidance_scale: 51000
console_preview: false
console_preview_width: 80
cuda_device: cuda:0
cut_ic_pow: 1
cut_icgray_p: '[0.2]*30+[0]*970'
cut_innercut: '[8]*30+[16]*970'
cut_overview: '[8]*30+[0]*970'
cutn_batches: 1
cutout_debug: false
# db: /content/gdrive/MyDrive/disco-diffusion-1/disco.db
#diffusion_model: 512x512_diffusion_uncond_finetune_008100
#diffusion_sampling_mode: ddim
display_rate: 50
eta: 0.2
extract_nth_frame: 2
#f: /root/.local/share/jupyter/runtime/kernel-d6f56a62-75e3-41ba-b009-d513f3dc9e61.json
far_plane: 10000
fov: 120
frames_scale: 35000
frames_skip_steps: 70%
fuzzy_prompt: false
image_prompts: {}
images_out: images_out
init_image:
init_images: init_images
init_scale: 55
intermediate_saves: 0
intermediates_in_subfolder: true
interp_spline: Linear
key_frames: true
max_frames: 10000
midas_depth_model: dpt_large
midas_weight: 0.3
model_path: models
modifiers: {}
multipliers: {}
n_batches: 1
near_plane: 200
padding_mode: border
#per_job_kills: false
#perlin_init: false
#perlin_mode: mixed
rand_mag: 0.1
randomize_class: true
range_scale: 1666
resume_from_frame: latest
resume_run: true
retain_overwritten_frames: false
rotation_3d_x: '0: (0)'
rotation_3d_y: '0: (0)'
rotation_3d_z: '0: (-0.002)'
run_to_resume: latest
sampling_mode: bicubic
sat_scale: 90000
save_metadata: false
set_seed: random_seed
simple_nvidia_smi_display: true
skip_augs: false
skip_steps: 10
skip_video_for_run_all: false
steps: 110
symmetry_loss: true
symmetry_loss_scale: 1500
symmetry_switch: 40
text_prompts:
  0:
  - "a cybernetic elephant walking through a cyberpunk city by Juan P. Osorio and thomas kinkade, 4k ultra, Trending on artstation."
  20:
  - "a cybernetic DJ performing in a cyberpunk city by Juan P. Osorio and syd mead, album cover, beautiful modern colors, 4k ultra, Trending on artstation."
translation_x: '0: (0)'
translation_y: '0: (0)'
translation_z: '0: (15.0)'
turbo_mode: false
turbo_preroll: 10
turbo_steps: 3
tv_scale: 75
twilio_account_sid: null
twilio_auth_token: null
twilio_from: null
twilio_to: null
useCPU: false
use_checkpoint: true
use_secondary_model: true
v_symmetry_loss: true
v_symmetry_loss_scale: 1500
v_symmetry_switch: 40
video_init_path: training.mp4
video_init_seed_continuity: true
vr_eye_angle: 0.5
vr_ipd: 5.0
vr_mode: false
width_height:
- 912
- 512
zoom: '"0: (1)'
```
