### ISSUE TITLE
Turbo mode not working

### ISSUE THREAD

**Issue by seandearnaley** [entmike/disco-diffusion-1#8]
I have mentioned this on the discord but I figured it was worth making a proper issue for it.    I have tested this now with colab and lambda labs.   Basically when you get to frame 10 (that's when turbo kicks in), it stops working, this is the error:

```
Traceback (most recent call last):
  File "disco.py", line 30, in <module>
    dd.start_run(pargs=pargs, folders=folders, device=device, is_colab=dd.detectColab())
  File "/workspace/disco-diffusion-1/dd.py", line 2157, in start_run
    processBatch(pargs=job, folders=folders, device=device, is_colab=is_colab, session_id=session_id)
  File "/workspace/disco-diffusion-1/dd.py", line 2399, in processBatch
    do_run(args=args, device=device, is_colab=is_colab, batchNum=batchNum, start_frame=start_frame, folders=folders)
  File "/workspace/disco-diffusion-1/dd.py", line 1446, in do_run
    old_frame = do_3d_step(
  File "/workspace/disco-diffusion-1/dd.py", line 491, in do_3d_step
    translation_x = translations.translation_x_series[frame_num]
AttributeError: 'NoneType' object has no attribute 'translation_x_series'
```

<img width="1703" alt="Screen Shot 2022-05-19 at 2 58 50 PM" src="https://user-images.githubusercontent.com/5084762/169381235-f4ed26d3-cc56-4a46-a9af-80cf3b471eb3.png">

YAML config:
```
RN101: false
RN50: true
RN50x16: false
RN50x4: false
RN50x64: false
ViTB16: true
ViTB32: true
ViTL14: false
ViTL14_336: false
angle: 0:(0)
animation_mode: 3D
batch_name: AnimTest7
check_model_SHA: false
clamp_grad: true
clamp_max: 0.26
clip_denoised: false
clip_guidance_scale: 51000
console_preview: false
console_preview_width: 80
cuda_device: cuda:0
cut_ic_pow: 1
cut_icgray_p: '[0.2]*30+[0]*970'
cut_innercut: '[8]*30+[16]*970'
cut_overview: '[8]*30+[0]*970'
cutn_batches: 1
cutout_debug: false
# db: /content/gdrive/MyDrive/disco-diffusion-1/disco.db
#diffusion_model: 512x512_diffusion_uncond_finetune_008100
#diffusion_sampling_mode: ddim
display_rate: 50
eta: 0.2
extract_nth_frame: 2
#f: /root/.local/share/jupyter/runtime/kernel-d6f56a62-75e3-41ba-b009-d513f3dc9e61.json
far_plane: 10000
fov: 120
frames_scale: 35000
frames_skip_steps: 70%
fuzzy_prompt: false
image_prompts: {}
images_out: images_out
init_image:
init_images: init_images
init_scale: 55
intermediate_saves: 0
intermediates_in_subfolder: true
interp_spline: Linear
key_frames: true
max_frames: 10000
midas_depth_model: dpt_large
midas_weight: 0.3
model_path: models
modifiers: {}
multipliers: {}
n_batches: 1
near_plane: 200
padding_mode: border
#per_job_kills: false
#perlin_init: false
#perlin_mode: mixed
rand_mag: 0.1
randomize_class: true
range_scale: 1666
resume_from_frame: latest
resume_run: true
retain_overwritten_frames: false
rotation_3d_x: '0: (0)'
rotation_3d_y: '0: (0)'
rotation_3d_z: '0: (-0.002)'
run_to_resume: latest
sampling_mode: bicubic
sat_scale: 90000
save_metadata: false
set_seed: random_seed
simple_nvidia_smi_display: true
skip_augs: false
skip_steps: 10
skip_video_for_run_all: false
steps: 110
symmetry_loss: true
symmetry_loss_scale: 1500
symmetry_switch: 40
text_prompts:
  0:
  - "a cybernetic elephant walking through a cyberpunk city by Juan P. Osorio and thomas kinkade, 4k ultra, Trending on artstation."
  1000:
  - "a cybernetic DJ performing in a cyberpunk city by Juan P. Osorio and syd mead, album cover, beautiful modern colors, 4k ultra, Trending on artstation."
translation_x: '0: (0)'
translation_y: '0: (0)'
translation_z: '0: (15.0)'
turbo_mode: true
turbo_preroll: 10
turbo_steps: 2
tv_scale: 75
twilio_account_sid: null
twilio_auth_token: null
twilio_from: null
twilio_to: null
useCPU: false
use_checkpoint: true
use_secondary_model: true
v_symmetry_loss: true
v_symmetry_loss_scale: 1500
v_symmetry_switch: 40
video_init_path: training.mp4
video_init_seed_continuity: true
vr_eye_angle: 0.5
vr_ipd: 5.0
vr_mode: false
width_height:
- 912
- 512
zoom: '"0: (1)'
```
